# SPDX-FileCopyrightText: 2021 Benedict Harcourt <ben.harcourt@harcourtprogramming.co.uk>
#
# SPDX-License-Identifier: CC0-1.0

printWidth: 120
useTabs: false
tabWidth: 4

semi: true
singleQuote: false
quoteProps: consistent
trailingComma: es5
bracketSpacing: true

bracketSameLine: false

arrowParens: avoid
